name: Promote to stage

on:
  push:
    branches: [ dev, master, breaking ]

jobs:
  build-images:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: setup-env
      run: |
        echo ZKSYNC_HOME=$(pwd) >> $GITHUB_ENV
        echo CI=1 >> $GITHUB_ENV
        echo $(pwd)/bin >> $GITHUB_PATH

    - name: init
      run: |
        cargo sqlx --version || cargo install --version=0.1.0-beta.1 sqlx-cli
        zk
        zk run yarn
        cp etc/tokens/{test,localhost}.json
        zk run verify-keys unpack
        zk db setup

    - name: update-images
      run: |
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
        zk docker push rust
        zk docker push nginx
        echo IMAGE_TAG=$(git rev-parse --short HEAD) >> $GITHUB_ENV

    - name: promote-to-gitlab
      run: |
        curl -X POST \
         -F token=${{ secrets.GITLAB_TOKEN }} \
         -F "ref=master" \
         -F "variables[SERVER_TAG]=$IMAGE_TAG" \
         -F "variables[PROVER_TAG]=$IMAGE_TAG" \
         -F "variables[EXPLORER_TAG]=$IMAGE_TAG" \
         -F "variables[GITHUB_REF]=$GITHUB_REF" \
         https://gitlab.com/api/v4/projects/19173848/trigger/pipeline

    services:
      postgres:
        image: postgres:10.4
        ports:
          - 5432:5432
